blank_issues_enabled: false
contact_links:
  - name: 🗣️ Ask question
    url: https://github.com/CarbonPackages/Carbon.Plausible/discussions/category_choices
    about: Please ask and answer questions in discussions
