- name: 'Set localStorage flag for disabling tracking'
  uriPattern: '{node}~/disable-tracking'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    'disablePlausibleTracking': true
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true

- name: 'API for reverse proxy'
  uriPattern: '~plausible'
  defaults:
    '@package': 'Carbon.Plausible'
    '@controller': 'ReverseProxy'
    '@action': 'apiEvent'
  httpMethods: ['POST']

- name: 'API for reverse proxy (For headless mode)'
  uriPattern: '~plausible/api/event'
  defaults:
    '@package': 'Carbon.Plausible'
    '@controller': 'ReverseProxy'
    '@action': 'apiEvent'
  httpMethods: ['POST']

- name: 'Files for reverse proxy'
  uriPattern: '~plausible({filename}).js'
  defaults:
    '@package': 'Carbon.Plausible'
    '@controller': 'ReverseProxy'
    '@action': 'file'
    'filename': 'default'
  httpMethods: ['GET']
