- name: 'Set localStorage flag for disabling tracking'
  uriPattern: '{node}~pls/disable-tracking'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    'plausible': 'disableTracking'
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true
  httpMethods: ['GET']

- name: 'Event API proxy'
  uriPattern: '{node}~pls/api/event'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    'plausible': 'apiEvent'
  httpMethods: ['POST']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true

- name: 'Javascript file proxy'
  uriPattern: '{node}~pls/js/script.js'
  defaults:
    '@package': 'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action': 'show'
    'plausible': 'script'
  httpMethods: ['GET']
  routeParts:
    node:
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: true
