Carbon:
  Plausible:
    # Enable or disable the Plausible integration
    # Disable per default, enabled in Production context per default
    enable: true

    # If you set  this to false, all inline javascript will not be rendered and you will have to add the Plausible tracking code manually in your templates
    renderInlineScriptTag: true

    # If you set this to false, the 404 event will not be sent to Plausible, even if the status code is between 400 and 499
    set404Event: true

    # Function to define the plausible object in the window, used for the embedded view of the stats in the backend
    # Usually you don't need to change this, but if you have a custom plausible tracking code, you can change it here
    definePlausibleJavscript: 'window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}}'

    default:
      # If you have opened up your website stats to the public or created a private
      # and secure link, enter it to enable the embedded view of the stats in the backend
      sharedLink: null

      # Add here your Plausible tracking code
      # To ad a multiline tracking code, use the following format:
      # trackingCode: |
      #   <!-- Privacy-friendly analytics by Plausible -->
      #   <script async src="https://plausible.io/js/pa-XXXXXXXX.js"></script>
      #   <script>
      #     window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
      #     plausible.init()
      #   </script>
      # You can also ad only the external script part <script async src="https://plausible.io/js/pa-XXXXXXXX.js"></script>
      # or the source only https://plausible.io/js/pa-XXXXXXXX.js
      trackingCode: null
