Carbon:
  Plausible:
    # Enable or disable the Plausible integration
    # Disable per default, enabled in Production context per default
    enable: false

    definePlausibleJavscript: 'window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}}'

    default:
      # If you have opened up your website stats to the public or created a private
      # and secure link, enter it to enable the embedded view of the stats in the backend
      sharedLink: null

      # Add here your Plausible tracking code
      # To ad a multiline tracking code, use the following format:
      # trackingCode: |
      #   <!-- Privacy-friendly analytics by Plausible -->
      #   <script async src="https://plausible.io/js/pa-XXXXXXXX.js"></script>
      #   <script>
      #     window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
      #     plausible.init()
      #   </script>
      # You can also ad only the external script part <script async src="https://plausible.io/js/pa-XXXXXXXX.js"></script>
      # or the source only https://plausible.io/js/pa-XXXXXXXX.js
      trackingCode: null
