Carbon:
  Plausible:
    enable: false
    default:
      domain: null
      host: null
      hashBasedRouting: false
      exclusions: false
      outboundLinks: false
      customEvents: false
      sharedLink: null
    # sites:
    #   rootNodeName:
    #     host: stats.domain.tld
    #     domain: domain.tld
    #     outboundLinks: true
