Neos:
  Fusion:
    defaultContext:
      Carbon.Plausible: 'Carbon\Plausible\EelHelper\PlausibleHelper'
  Flow:
    mvc:
      routes:
        'Carbon.Plausible':
          position: 'start 1'
  Neos:
    fusion:
      autoInclude:
        Carbon.Plausible: true
    userInterface:
      translation:
        autoInclude:
          Carbon.Plausible:
            - Main
            - 'NodeTypes/*'
