Neos:
  Neos:
    fusion:
      autoInclude:
        Carbon.Plausible: true
    userInterface:
      translation:
        autoInclude:
          Carbon.Plausible:
            - Main
            - 'NodeTypes/*'
    modules:
      administration:
        submodules:
          plausible:
            label: Plausible
            description: 'Check your configuration for Plausible and disable/enable tracking from this browser'
            icon: 'fas fa-chart-pie'
            controller: \Carbon\Plausible\Controller\PlausibleController
            privilegeTarget: 'Carbon.Plausible:ViewConfiguration'
            position: end
            mainStylesheet: Lite
            additionalResources:
              javaScripts:
                - 'resource://Carbon.Plausible/Public/Module.js'
              styleSheets:
                - 'resource://Carbon.Plausible/Public/Module.css'
