Neos:
  Fusion:
    defaultContext:
      Carbon.Plausible: 'Carbon\Plausible\EelHelper\PlausibleHelper'
  Flow:
    mvc:
      routes:
        'Carbon.Plausible':
          position: 'start 1'
  Neos:
    fusion:
      autoInclude:
        Carbon.Plausible: true
    userInterface:
      translation:
        autoInclude:
          Carbon.Plausible:
            - Main
            - 'NodeTypes/*'
    Ui:
      resources:
        javascript:
          Carbon.Plausible:Editor:
            resource: resource://Carbon.Plausible/Public/Plugin.js
            attributes:
              type: 'module'
        stylesheets:
          Carbon.Plausible:Editor:
            resource: resource://Carbon.Plausible/Public/stylex.css
